name: Check million digit

# 新しいコミットがリポジトリにプッシュされるたびにこのワークフローを実行する
on: push

jobs:
  # ジョブキーを設定する。 ジョブ名が指定されていない場合、
  # キーはジョブ名として表示される
  super-lint:
    # ジョブ名を付ける
    name: Lint code base
    # 実行するマシンのタイプを設定する
    runs-on: ubuntu-latest

    steps:
      # ubuntu-latest マシンでリポジトリのコピーをチェックアウトする
      - name: Checkout code
        uses: actions/checkout@v2
      - run: sudo apt-get install g++-8 libboost-dev
      - run: make pi
      - run: ./pi 10000 1 > out.txt